### ISSUE TITLE
Can't login after session expires

### ISSUE THREAD

**Issue by flamingspaz** [mozilla-iam/mozilla.oidc.accessproxy#4] opened 2017-11-06 19:06 UTC
After logging in with LDAP, at some point the session will expire, and the proxy will constantly redirect to the forbidden page. Logging out of the proxy or dashboard doesn't seem to help, Leo managed to work around it by clearing cookies. Everything seems to work fine with passwordless.

**Comment by gdestuynder** [comment] 2017-11-06 21:44
when `prompt=none` fails (your auth0 session is no longer valid) it sends you back to `redirect_uri` which in turns sends you back to `/logout` which finally, sends you back to `sso.mozilla.com/forbidden` by default

You can change the forbidden URL by your login URL and the user will be prompted to re-authenticate with auth0 (i.e. the expected behavior). Because the login URL depends on the RP and not necessarily the proxy directly its not easy to hardcode to something really meaningful, though we could also patch the upstream library to send you back automatically to the OIDC OP (more generic method, though that means no opportunity to tell the user what happened)

**Comment by gdestuynder** [comment] 2017-11-06 21:45
when `prompt=none` fails (your auth0 session is no longer valid) it sends you back to `redirect_uri` which in turns sends you back to `/logout` which finally, sends you back to `sso.mozilla.com/forbidden` by default

You can change the forbidden URL by your login URL and the user will be prompted to re-authenticate with auth0 (i.e. the expected behavior). Because the login URL depends on the RP and not necessarily the proxy directly its not easy to hardcode to something really meaningful, though we could also patch the upstream library to send you back automatically to the OIDC OP (more generic method, though that means no opportunity to tell the user what happened - basically send the user back with `prompt=login`)

**Comment by gdestuynder** [comment] 2017-11-06 22:24
Looked at this a little more and:
We probably hit https://github.com/mozilla-iam/mozilla.oidc.accessproxy/blob/master/etc/conf.d/openidc_layer.lua#L14 when that happens
We could maybe figure out the `error_code` there and send the user back to login instead if the code is `login_required`

**Comment by flamingspaz** [comment] 2017-11-07 09:38
Awesome thx, I'll do the workaround and see if I can't get to handling the error correctly sometime soon.

**Comment by gdestuynder** [comment] 2017-11-07 20:59
I think Alicia in our team ran into this as well today. If i get access to our machine i can try to see if i fix it there and PR - unless you get to it first

**Comment by gdestuynder** [comment] 2017-11-10 22:40
its bug in the lua-resty-openidc library will pr fix

**Comment by gdestuynder** [comment] 2017-11-10 23:25
PR'd upstream at https://github.com/pingidentity/lua-resty-openidc/pull/119
It has full info on why/how this is happening
I consider this closed even thus its not actually fixed until the PR is merged and released :/

in the mean time you can manually merge it, as my above comments wont in fact "fix the problem" (or even work around it)

**Closed by gdestuynder** 2017-11-10 23:25 UTC
